import { ComparisonReport } from './types';

// Generate CSV string from comparison results
export function generateResultsCSV(report: ComparisonReport): string {
  if (report.taskType === 'regression') {
    const headers = ['Model', 'Algorithm Description', 'MAE', 'RMSE', 'R2 Score', 'Training Time (ms)', 'Is Best'];
    const rows = report.models.map(m => {
      const reg = m.result.taskType === 'regression' ? m.result.metrics : { mae: 0, rmse: 0, r2: 0 };
      return [
        `"${m.name}"`,
        `"${m.shortDescription}"`,
        reg.mae.toFixed(3),
        reg.rmse.toFixed(3),
        reg.r2.toFixed(3),
        m.trainingTimeMs,
        m.isBest ? 'YES' : 'NO'
      ].join(',');
    });
    return [headers.join(','), ...rows].join('\n');
  } else {
    const headers = ['Model', 'Algorithm Description', 'Accuracy', 'Precision', 'Recall', 'F1 Score', 'Training Time (ms)', 'Is Best'];
    const rows = report.models.map(m => {
      const clf = m.result.taskType === 'classification' ? m.result.metrics : { accuracy: 0, precision: 0, recall: 0, f1: 0 };
      return [
        `"${m.name}"`,
        `"${m.shortDescription}"`,
        clf.accuracy.toFixed(3),
        clf.precision.toFixed(3),
        clf.recall.toFixed(3),
        clf.f1.toFixed(3),
        m.trainingTimeMs,
        m.isBest ? 'YES' : 'NO'
      ].join(',');
    });
    return [headers.join(','), ...rows].join('\n');
  }
}

// Generate comprehensive Markdown / Text Report
export function generateMarkdownReport(report: ComparisonReport): string {
  const dateStr = new Date(report.timestamp).toLocaleString();
  const isReg = report.taskType === 'regression';

  let md = `# Supervised ML Model Comparison Report\n\n`;
  md += `**Generated**: ${dateStr}\n`;
  md += `**Task Type**: ${report.taskType.toUpperCase()}\n`;
  md += `**Dataset**: ${report.datasetName}\n`;
  md += `**Target Variable**: \`${report.targetColumn}\`\n`;
  md += `**Sample Partition**: Total = ${report.sampleCount} rows | Train (80%) = ${report.trainCount} | Test (20%) = ${report.testCount}\n`;
  md += `**Feature Count**: ${report.featureCount} numeric standardized features\n\n`;

  md += `## 1. Executive Summary & Best Model\n\n`;
  md += `- **Top-Performing Model**: **${report.bestModelName}**\n`;
  md += `- **Why it performed best**: ${report.explanation.winnerReason}\n`;
  md += `- **Areas of underperformance**: ${report.explanation.loserReason}\n`;
  md += `- **Bias-Variance Takeaway**: ${report.explanation.tradeoffSummary}\n\n`;

  md += `## 2. Model Performance Evaluation Table\n\n`;

  if (isReg) {
    md += `| Model | MAE | RMSE | R² Score | Train Time | Rank |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- | :--- |\n`;
    report.models.forEach((m, idx) => {
      const reg = m.result.taskType === 'regression' ? m.result.metrics : { mae: 0, rmse: 0, r2: 0 };
      const star = m.isBest ? '★ Best' : `#${idx + 1}`;
      md += `| **${m.name}** | ${reg.mae.toFixed(3)} | ${reg.rmse.toFixed(3)} | **${reg.r2.toFixed(3)}** | ${m.trainingTimeMs} ms | ${star} |\n`;
    });
  } else {
    md += `| Model | Accuracy | Precision | Recall | F1 Score | Train Time | Rank |\n`;
    md += `| :--- | :--- | :--- | :--- | :--- | :--- | :--- |\n`;
    report.models.forEach((m, idx) => {
      const clf = m.result.taskType === 'classification' ? m.result.metrics : { accuracy: 0, precision: 0, recall: 0, f1: 0 };
      const star = m.isBest ? '★ Best' : `#${idx + 1}`;
      md += `| **${m.name}** | **${(clf.accuracy * 100).toFixed(1)}%** | ${(clf.precision * 100).toFixed(1)}% | ${(clf.recall * 100).toFixed(1)}% | ${clf.f1.toFixed(3)} | ${m.trainingTimeMs} ms | ${star} |\n`;
    });
  }

  md += `\n## 3. Methodology & Preprocessing Pipeline\n\n`;
  md += `1. **Train/Test Splitting**: Partitioned 80% for training and 20% held out for unseen testing ${isReg ? 'using random shuffling' : 'with class stratification'}.\n`;
  md += `2. **Feature Standardization**: Features were scaled using Z-score standardization: (x - mean) / std. Scaler parameters were fit solely on the training partition to avoid data leakage.\n`;
  md += `3. **Evaluation Protocol**: Metrics were computed strictly on the held-out 20% test partition.\n\n`;

  md += `---\n*Generated by Supervised ML Model Comparison System*\n`;

  return md;
}

// Download helper to trigger file download in browser
export function triggerDownload(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
